# Generated by Django 5.2.4 on 2025-07-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placeimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
